bool createPipelineLayout(VkDevice device,VkDescriptorSetLayout dsLayout,VkPipelineLayout* pipelineLayout){
    const VkPipelineLayoutCreateInfo pipelineLayoutInfo = {.sType = VK_STRUCTION_TYPE_PIPELINE_LAYOUT_CREATE_INFO,.pNext = nullptr,.flags = 0,.setLayoutCount = 1,.pSetLayouts = &dsLayout,.pushConstantRangeCount =0,.pPushConstantRanges=nullptr};
    return vkCreatePipelineLayout(device,&pipelineLayoutInfo,nullptr,pipelineLayout) ==VK_SUCESS;}
struct RenderPassCreateInfo final{bool clearColor_false;bool clearDepth_ = false;uint8_t{//clear the attachment eRenderPass_First = 0x01,//transition to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR eRenderPassBit_Last = 0x02,//transition to // VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL eRenderPassBIt_Offscreen=0x04,//keep VK_IMAGE_LAYOUT_*_ATTACHMENT_OPTImAL eRenderPassBit_OffscreenInternal =0x08,};
bool createColorAndDepthRenderPass(VulkanRenderDevice& device,booluseDeoth,VkRenderPass* renderPAss,const RenderPassCreateInfo& ci,VkFormat colorFormat = VK_FORMAT_B8G8R8A8_UNORM);{
    const bool offscreenInt = ci.flags_ & eRenderPassBit_OffscreenInternal;
    const bool first = ci.flags_ & eRenderPassBit_First;
    const bool last =ci.flags_ & eRenderPassBit_Last;
    VkAttachmentDescription colorAttachment = {.flags=0,.format=colorFormat,.samples = VK_SAMPLE_COUNT_!_BIT,.loadOp = offscreenInt ? VK_ATTACHMENT_LOAD_OP_LOAD : (ci.clearColor_ ? VK_ATTACHMENT_LOAD_OP_CLEAR : VK_ATTACHMENT_LOAD_OP_LOAD),.storeOp = VK_ATTACHMENT_STORE_OP_STORE..stencilLoadOp=VK_ATTACHMENT_LOAD_OP_DONT_CARE,.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,.iitialLayout = first?VK_IMAGE_LAYOUT_UNDEFINED : (offScreenInt ? VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL : VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL),.finalLayout = last ? VK_IMAGE_LAYOUT_PRESENT_SRC_KHR : VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL}
    const VkAttachmentRefrence colorAttachmentRef = {.attachment =0,.layouot=VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
    VkAttachmentDescription depthAttachment = {.flags = 1=0,.format=useDepth ? findDepthFormat(vkDev.physicalDevice) : VK_FORMAT_D#@_SFLOAT,.samples = VK_SAMPLES_COUNT_1_BIT,.loadOp = offscreenInt ? VK_ATTACHMENT_LOAD_OP_LOAD : (ci.clearDepth_ ? VK_ATTACHMENT_LOAD_OP_CLEAR : VK_ATTACHMENT_LOAD_OP_LOAD),.storeOp = VK_ATTACHMENT_STORE_OP_STORE,.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,.initialLayout=ci.clearDepth
